-- Mecanikall · esquema inicial de Supabase
-- Ejecuta este archivo completo en Supabase: SQL Editor > New query.
-- Es seguro volver a ejecutarlo: no elimina datos existentes.

create extension if not exists pgcrypto;

do $$ begin
  create type public.tipo_estatus_ticket as enum ('Abierto', 'Asignado', 'Concluido', 'Cancelado');
exception when duplicate_object then null;
end $$;

create table if not exists public.clientes (
  id_cliente bigint generated by default as identity primary key,
  nombre_completo text not null check (char_length(trim(nombre_completo)) >= 2),
  telefono_whatsapp text not null unique check (telefono_whatsapp ~ '^[0-9]{10}$'),
  created_at timestamptz not null default now()
);

create table if not exists public.mecanicos (
  id_mecanico bigint generated by default as identity primary key,
  -- UUID del usuario creado en Authentication > Users. Debe ser único.
  id_usuario uuid unique references auth.users(id) on delete cascade,
  nombre_taller text not null,
  whatsapp_destino text not null check (whatsapp_destino ~ '^[0-9]{10,15}$'),
  especialidades text[] not null default '{}',
  palabras_clave text[] not null default '{}',
  estatus_suscripcion text not null default 'Activo' check (estatus_suscripcion in ('Activo', 'Suspendido', 'Pendiente')),
  zona_cobertura text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.tickets (
  id_ticket bigint generated by default as identity primary key,
  id_cliente bigint not null references public.clientes(id_cliente) on delete restrict,
  descripcion_falla text not null check (char_length(trim(descripcion_falla)) >= 10),
  ubicacion_auto text not null check (char_length(trim(ubicacion_auto)) >= 3),
  estatus public.tipo_estatus_ticket not null default 'Abierto',
  id_mecanico_asignado bigint references public.mecanicos(id_mecanico) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ticket_asignacion_consistente check (
    (estatus = 'Asignado' and id_mecanico_asignado is not null)
    or (estatus <> 'Asignado')
  )
);

-- Compatibilidad si las tres tablas ya existían antes de usar este archivo.
alter table public.mecanicos add column if not exists id_usuario uuid unique references auth.users(id) on delete cascade;
alter table public.tickets add column if not exists updated_at timestamptz not null default now();

create index if not exists tickets_abiertos_idx on public.tickets (created_at asc) where estatus = 'Abierto';
create index if not exists tickets_mecanico_idx on public.tickets (id_mecanico_asignado);
create index if not exists mecanicos_usuario_idx on public.mecanicos (id_usuario);

create or replace function public.actualizar_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tickets_updated_at on public.tickets;
create trigger tickets_updated_at before update on public.tickets
for each row execute function public.actualizar_updated_at();

-- Seguridad. El cliente actual no inicia sesión; por eso puede crear y leer
-- solicitudes. Antes de un lanzamiento público, cambia este flujo a usuarios
-- anónimos de Supabase Auth para restringir cada ticket a su propietario.
alter table public.clientes enable row level security;
alter table public.mecanicos enable row level security;
alter table public.tickets enable row level security;

drop policy if exists "Clientes públicos pueden consultar" on public.clientes;
create policy "Clientes públicos pueden consultar" on public.clientes
for select to anon, authenticated using (true);

drop policy if exists "Clientes públicos pueden crearse" on public.clientes;
create policy "Clientes públicos pueden crearse" on public.clientes
for insert to anon, authenticated with check (true);

drop policy if exists "Perfil del taller autenticado" on public.mecanicos;
create policy "Perfil del taller autenticado" on public.mecanicos
for select to authenticated using (id_usuario = auth.uid());

-- Datos mínimos del taller que el cliente necesita tras aceptar el ticket.
drop policy if exists "Datos de contacto de talleres" on public.mecanicos;
create policy "Datos de contacto de talleres" on public.mecanicos
for select to anon using (true);

drop policy if exists "Tickets visibles para el flujo MVP" on public.tickets;
create policy "Tickets visibles para el flujo MVP" on public.tickets
for select to anon, authenticated using (true);

drop policy if exists "Clientes pueden crear tickets" on public.tickets;
create policy "Clientes pueden crear tickets" on public.tickets
for insert to anon, authenticated with check (estatus = 'Abierto' and id_mecanico_asignado is null);

drop policy if exists "Taller acepta tickets abiertos" on public.tickets;
create policy "Taller acepta tickets abiertos" on public.tickets
for update to authenticated
using (estatus = 'Abierto')
with check (
  estatus = 'Asignado'
  and id_mecanico_asignado in (select id_mecanico from public.mecanicos where id_usuario = auth.uid())
);

-- Realtime: necesario para que cliente y taller vean asignaciones sin recargar.
do $$ begin
  alter publication supabase_realtime add table public.tickets;
exception when duplicate_object then null;
end $$;

-- PASOS DESPUÉS DE EJECUTAR:
-- 1. Crea un usuario de taller en Authentication > Users.
-- 2. Inserta el taller y asocia el UUID creado:
-- En una base que use el enum tipo_especialidad, usa:
-- insert into public.mecanicos (id_usuario, nombre_taller, whatsapp_destino, especialidades, palabras_clave, zona_cobertura)
-- values ('UUID-DE-AUTH-USERS', 'Taller Ejemplo', '5215512345678', array['Frenos']::public.tipo_especialidad[], array['freno', 'balatas'], 'Ciudad de México');
