-- Mecanikall · esquema inicial de Supabase
-- Ejecuta este archivo completo en Supabase: SQL Editor > New query.
-- Es seguro volver a ejecutarlo: no elimina datos existentes.

create extension if not exists pgcrypto;

do $$ begin
  create type public.tipo_estatus_ticket as enum ('Abierto', 'Asignado', 'Concluido', 'Cancelado');
exception when duplicate_object then null;
end $$;

create table if not exists public.clientes (
  id_cliente bigint generated by default as identity primary key,
  nombre_completo text not null check (char_length(trim(nombre_completo)) >= 2),
  telefono_whatsapp text not null unique check (telefono_whatsapp ~ '^[0-9]{10}$'),
  created_at timestamptz not null default now()
);

create table if not exists public.mecanicos (
  id_mecanico bigint generated by default as identity primary key,
  -- UUID del usuario creado en Authentication > Users. Debe ser único.
  id_usuario uuid unique references auth.users(id) on delete cascade,
  nombre_taller text not null,
  whatsapp_destino text not null check (whatsapp_destino ~ '^[0-9]{10,15}$'),
  especialidades text[] not null default '{}',
  palabras_clave text[] not null default '{}',
  estatus_suscripcion text not null default 'Activo' check (estatus_suscripcion in ('Activo', 'Suspendido', 'Pendiente')),
  zona_cobertura text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.tickets (
  id_ticket bigint generated by default as identity primary key,
  id_cliente bigint not null references public.clientes(id_cliente) on delete restrict,
  descripcion_falla text not null check (char_length(trim(descripcion_falla)) >= 10),
  ubicacion_auto text not null check (char_length(trim(ubicacion_auto)) >= 3),
  estatus public.tipo_estatus_ticket not null default 'Abierto',
  id_mecanico_asignado bigint references public.mecanicos(id_mecanico) on delete set null,
  id_usuario_solicitante uuid references auth.users(id) on delete set null,
  canal_origen text not null default 'Web' check (canal_origen in ('Web', 'WhatsApp')),
  ai_sesion_id text,
  ai_prediagnostico jsonb,
  ai_urgencia text check (ai_urgencia is null or ai_urgencia in ('low', 'medium', 'high')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ticket_asignacion_consistente check (
    (estatus = 'Asignado' and id_mecanico_asignado is not null)
    or (estatus <> 'Asignado')
  )
);

-- Compatibilidad si las tres tablas ya existían antes de usar este archivo.
alter table public.mecanicos add column if not exists id_usuario uuid unique references auth.users(id) on delete cascade;
alter table public.tickets add column if not exists updated_at timestamptz not null default now();
alter table public.tickets add column if not exists id_usuario_solicitante uuid references auth.users(id) on delete set null;

create index if not exists tickets_abiertos_idx on public.tickets (created_at asc) where estatus = 'Abierto';
create index if not exists tickets_mecanico_idx on public.tickets (id_mecanico_asignado);
create index if not exists tickets_solicitante_idx on public.tickets (id_usuario_solicitante);
create unique index if not exists tickets_ai_sesion_unica_idx on public.tickets (ai_sesion_id) where ai_sesion_id is not null;
create unique index if not exists clientes_telefono_whatsapp_unique_idx on public.clientes (telefono_whatsapp);
create index if not exists mecanicos_usuario_idx on public.mecanicos (id_usuario);

create or replace function public.actualizar_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tickets_updated_at on public.tickets;
create trigger tickets_updated_at before update on public.tickets
for each row execute function public.actualizar_updated_at();

-- Seguridad: cada solicitante usa una sesión anónima de Supabase Auth. Los datos
-- personales solo se exponen al taller que toma la solicitud mediante funciones.
alter table public.clientes enable row level security;
alter table public.mecanicos enable row level security;
alter table public.tickets enable row level security;

drop policy if exists "Clientes públicos pueden consultar" on public.clientes;
drop policy if exists "Clientes públicos pueden crearse" on public.clientes;
drop policy if exists "Perfil del taller autenticado" on public.mecanicos;
create policy "Perfil del taller autenticado" on public.mecanicos
for select to authenticated using (id_usuario = auth.uid());

-- Datos mínimos del taller que el cliente necesita tras aceptar el ticket.
drop policy if exists "Datos de contacto de talleres" on public.mecanicos;
create policy "Solicitante ve taller asignado" on public.mecanicos
for select to authenticated using (
  exists (select 1 from public.tickets where id_mecanico_asignado = mecanicos.id_mecanico and id_usuario_solicitante = auth.uid())
);

drop policy if exists "Tickets visibles para el flujo MVP" on public.tickets;
drop policy if exists "Clientes pueden crear tickets" on public.tickets;
drop policy if exists "Taller acepta tickets abiertos" on public.tickets;
create policy "Solicitante ve sus tickets" on public.tickets
for select to authenticated using (id_usuario_solicitante = auth.uid());

create or replace function public.solicitar_ayuda(p_nombre text, p_telefono text, p_ubicacion text, p_descripcion text)
returns setof public.tickets language plpgsql security definer set search_path = public as $$
declare v_cliente bigint; v_ticket public.tickets;
begin
  if auth.uid() is null then raise exception 'Se requiere una sesión activa'; end if;
  if p_telefono !~ '^[0-9]{10}$' then raise exception 'Teléfono inválido'; end if;
  insert into public.clientes (nombre_completo, telefono_whatsapp) values (trim(p_nombre), p_telefono)
  on conflict (telefono_whatsapp) do update set nombre_completo = excluded.nombre_completo
  returning id_cliente into v_cliente;
  insert into public.tickets (id_cliente, id_usuario_solicitante, ubicacion_auto, descripcion_falla)
  values (v_cliente, auth.uid(), trim(p_ubicacion), trim(p_descripcion)) returning * into v_ticket;
  return next v_ticket;
end;
$$;

create or replace function public.tickets_abiertos_para_taller()
returns table (id_ticket bigint, id_cliente bigint, descripcion_falla text, ubicacion_auto text, estatus public.tipo_estatus_ticket, id_mecanico_asignado bigint, created_at timestamptz, updated_at timestamptz, cliente jsonb)
language sql security definer set search_path = public as $$
  select t.id_ticket, t.id_cliente, t.descripcion_falla, t.ubicacion_auto, t.estatus, t.id_mecanico_asignado, t.created_at, t.updated_at,
    jsonb_build_object('nombre_completo', c.nombre_completo, 'telefono_whatsapp', c.telefono_whatsapp)
  from public.tickets t join public.clientes c on c.id_cliente = t.id_cliente
  where t.estatus = 'Abierto' and exists (select 1 from public.mecanicos m where m.id_usuario = auth.uid() and m.estatus_suscripcion = 'Activo')
  order by t.created_at asc;
$$;

create or replace function public.aceptar_ticket(p_id_ticket bigint)
returns setof public.tickets language plpgsql security definer set search_path = public as $$
declare v_mecanico bigint; v_ticket public.tickets;
begin
  select id_mecanico into v_mecanico from public.mecanicos where id_usuario = auth.uid() and estatus_suscripcion = 'Activo';
  if v_mecanico is null then raise exception 'Taller no autorizado'; end if;
  update public.tickets set estatus = 'Asignado', id_mecanico_asignado = v_mecanico
  where id_ticket = p_id_ticket and estatus = 'Abierto' returning * into v_ticket;
  if not found then raise exception 'La solicitud ya no está disponible' using errcode = 'P0002'; end if;
  return next v_ticket;
end;
$$;

create or replace function public.cancelar_ticket(p_id_ticket bigint)
returns setof public.tickets language plpgsql security definer set search_path = public as $$
declare v_ticket public.tickets;
begin
  update public.tickets set estatus = 'Cancelado'
  where id_ticket = p_id_ticket and id_usuario_solicitante = auth.uid() and estatus = 'Abierto'
  returning * into v_ticket;
  if not found then raise exception 'La solicitud ya no se puede cancelar' using errcode = 'P0002'; end if;
  return next v_ticket;
end;
$$;

create or replace function public.tickets_asignados_del_taller()
returns table (id_ticket bigint, id_cliente bigint, descripcion_falla text, ubicacion_auto text, estatus public.tipo_estatus_ticket, id_mecanico_asignado bigint, created_at timestamptz, updated_at timestamptz, cliente jsonb)
language sql security definer set search_path = public as $$
  select t.id_ticket, t.id_cliente, t.descripcion_falla, t.ubicacion_auto, t.estatus, t.id_mecanico_asignado, t.created_at, t.updated_at,
    jsonb_build_object('nombre_completo', c.nombre_completo, 'telefono_whatsapp', c.telefono_whatsapp)
  from public.tickets t join public.clientes c on c.id_cliente = t.id_cliente join public.mecanicos m on m.id_mecanico = t.id_mecanico_asignado
  where t.estatus = 'Asignado' and m.id_usuario = auth.uid() order by t.created_at desc;
$$;

create or replace function public.concluir_ticket(p_id_ticket bigint)
returns setof public.tickets language plpgsql security definer set search_path = public as $$
declare v_ticket public.tickets;
begin
  update public.tickets set estatus = 'Concluido'
  where id_ticket = p_id_ticket and estatus = 'Asignado' and id_mecanico_asignado in (select id_mecanico from public.mecanicos where id_usuario = auth.uid() and estatus_suscripcion = 'Activo')
  returning * into v_ticket;
  if not found then raise exception 'El servicio no se puede concluir' using errcode = 'P0002'; end if;
  return next v_ticket;
end;
$$;

revoke all on function public.solicitar_ayuda(text, text, text, text) from public;
grant execute on function public.solicitar_ayuda(text, text, text, text) to authenticated;
revoke all on function public.tickets_abiertos_para_taller() from public;
grant execute on function public.tickets_abiertos_para_taller() to authenticated;
revoke all on function public.aceptar_ticket(bigint) from public;
grant execute on function public.aceptar_ticket(bigint) to authenticated;
revoke all on function public.cancelar_ticket(bigint) from public;
grant execute on function public.cancelar_ticket(bigint) to authenticated;
revoke all on function public.tickets_asignados_del_taller() from public;
grant execute on function public.tickets_asignados_del_taller() to authenticated;
revoke all on function public.concluir_ticket(bigint) from public;
grant execute on function public.concluir_ticket(bigint) to authenticated;

-- Realtime: necesario para que cliente y taller vean asignaciones sin recargar.
do $$ begin
  alter publication supabase_realtime add table public.tickets;
exception when duplicate_object then null;
end $$;

-- PASOS DESPUÉS DE EJECUTAR:
-- 1. Crea un usuario de taller en Authentication > Users.
-- 2. Inserta el taller y asocia el UUID creado:
-- En una base que use el enum tipo_especialidad, usa:
-- insert into public.mecanicos (id_usuario, nombre_taller, whatsapp_destino, especialidades, palabras_clave, zona_cobertura)
-- values ('UUID-DE-AUTH-USERS', 'Taller Ejemplo', '5215512345678', array['Frenos']::public.tipo_especialidad[], array['freno', 'balatas'], 'Ciudad de México');
