import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { HistorialRefaccionesTienda, SolicitudRefaccionesTienda } from '../../models';
import { SupabaseService } from '../../services/supabase.service';

@Component({
  selector: 'app-panel-refacciones', standalone: true, imports: [ReactiveFormsModule], changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<main class="min-h-dvh bg-slate-950 px-5 py-8 text-slate-50"><section class="mx-auto max-w-3xl"><header class="flex justify-between gap-4"><div><p class="text-xs font-bold tracking-[.2em] text-cyan-300">REFACCIONES</p><h1 class="mt-2 text-2xl font-bold">Solicitudes de talleres</h1></div><button class="text-sm text-slate-400" (click)="salir()">Cerrar sesión</button></header>@if(error()){<p class="mt-5 rounded-xl bg-red-500/10 p-3 text-red-200">{{error()}}</p>}<button class="mt-6 rounded-lg border border-cyan-400 px-3 py-2 text-sm text-cyan-200" (click)="cargar()">Actualizar</button>@if(!solicitudes().length){<p class="mt-6 text-slate-400">No hay solicitudes disponibles.</p>}@else{<div class="mt-6 grid gap-4">@for(s of solicitudes();track s.id_solicitud){<form class="rounded-2xl border border-slate-700 bg-slate-800 p-5" [formGroup]="formulario(s.id_solicitud)" (ngSubmit)="enviar(s.id_solicitud)"><div class="flex justify-between gap-3"><p class="font-bold">{{s.nombre_taller}}</p><span class="text-sm text-cyan-200">Ticket #{{s.id_ticket}}</span></div><p class="mt-3 text-sm text-slate-300">{{s.descripcion}}</p><p class="mt-2 text-xs text-slate-400">{{s.ubicacion_auto}}</p><div class="mt-4 grid grid-cols-2 gap-3"><input class="rounded-lg bg-slate-900 p-3" formControlName="precio" type="number" min="0" placeholder="Precio MXN"/><input class="rounded-lg bg-slate-900 p-3" formControlName="minutos" type="number" min="1" placeholder="Entrega min"/></div><input class="mt-3 w-full rounded-lg bg-slate-900 p-3" formControlName="mensaje" placeholder="Mensaje opcional"/><button class="mt-3 w-full rounded-lg bg-cyan-400 p-3 font-bold text-slate-950 disabled:opacity-50" [disabled]="formulario(s.id_solicitud).invalid || enviando()===s.id_solicitud">{{enviando()===s.id_solicitud?'Enviando…':'Enviar cotización'}}</button></form>}</div>}<div class="mt-8"><h2 class="text-xl font-bold">Historial de cotizaciones</h2>@for(h of historial();track h.id_oferta){<p class="mt-3 rounded-lg bg-slate-800 p-3 text-sm">{{h.nombre_taller}} · MXN {{h.precio_estimado}} · {{h.estatus_oferta}}</p>}</div></section></main>`,
})
export class PanelRefaccionesComponent {
  private readonly supabase=inject(SupabaseService); private readonly fb=inject(FormBuilder); private readonly router=inject(Router);
  readonly solicitudes=signal<SolicitudRefaccionesTienda[]>([]); readonly historial=signal<HistorialRefaccionesTienda[]>([]); readonly error=signal<string|null>(null); readonly enviando=signal<number|null>(null); private readonly formularios=new Map<number, FormGroup>();
  constructor(){void this.cargar();}
  formulario(id:number){if(!this.formularios.has(id)) this.formularios.set(id,this.fb.nonNullable.group({precio:[0,[Validators.required,Validators.min(0)]],minutos:[60,[Validators.required,Validators.min(1)]],mensaje:['']})); return this.formularios.get(id)!;}
  async cargar(){try{const[s,h]=await Promise.all([this.supabase.obtenerSolicitudesRefaccionesParaTienda(),this.supabase.historialRefaccionesTienda()]);this.solicitudes.set(s);this.historial.set(h);}catch{this.error.set('No pudimos cargar las solicitudes.');}}
  async enviar(id:number){const f=this.formulario(id);if(f.invalid)return;this.enviando.set(id);try{const v=f.getRawValue();await this.supabase.enviarOfertaRefacciones(id,v.precio,v.minutos,v.mensaje);await this.cargar();}catch{this.error.set('No fue posible enviar la cotización.');}finally{this.enviando.set(null);}}
  async salir(){await this.supabase.cerrarSesion();await this.router.navigateByUrl('/acceso');}
}
