import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { ProspectoSuscripcion, SeguimientoComercial, Vendedor } from '../../models';
import { SupabaseService } from '../../services/supabase.service';

@Component({ selector:'app-reporte-suscripciones', standalone:true, imports:[FormsModule,RouterLink], changeDetection:ChangeDetectionStrategy.OnPush, template:`
<main class="min-h-dvh bg-slate-950 px-5 py-8 text-slate-50"><section class="mx-auto max-w-3xl"><a routerLink="/admin" class="text-sm text-orange-400">← Administración</a><h1 class="mt-6 text-2xl font-bold">Prospectos de suscripción</h1><p class="mt-2 text-sm text-slate-400">Asigna los talleres interesados a un vendedor antes de que inicien su suscripción.</p><div class="mt-5 flex gap-3"><input class="rounded-lg bg-slate-800 p-3" type="month" [(ngModel)]="mes" (change)="cargar()"><button class="rounded-lg bg-orange-500 px-4 font-bold text-slate-950" (click)="cargar()">Actualizar</button></div>@if(error()){<p class="mt-5 text-red-200">{{error()}}</p>}<div class="mt-6 grid gap-3">@for(p of prospectos();track p.tipo+p.id_entidad){<article class="rounded-xl border border-slate-700 bg-slate-800 p-4"><div class="flex justify-between gap-4"><div><p class="font-bold">{{p.nombre}}</p><p class="text-sm text-slate-400">{{p.tipo}} · {{p.zona_cobertura}}</p><a class="text-sm text-emerald-300" [href]="whatsapp(p)" target="_blank">WhatsApp</a></div><strong class="text-2xl text-orange-400">{{p.atenciones}}</strong></div><div class="mt-4 grid gap-2">@if(esAdmin()&&p.tipo==='Taller'){<select class="rounded bg-slate-900 p-2" [value]="seguimiento(p).id_responsable??''" (change)="asignar(p,$any($event.target).value)"><option value="">Asignar vendedor…</option>@for(v of vendedores();track v.id_usuario){<option [value]="v.id_usuario">{{v.email}}</option>}</select>}@else if(seguimiento(p).responsable_email){<p class="text-sm text-cyan-200">Vendedor: {{seguimiento(p).responsable_email}}</p>}<select class="rounded bg-slate-900 p-2" [value]="seguimiento(p).estado" (change)="cambiar(p,'estado',$any($event.target).value)">@for(e of estados;track e){<option [value]="e">{{e}}</option>}</select><input class="rounded bg-slate-900 p-2" type="date" [value]="seguimiento(p).proxima_accion" (change)="cambiar(p,'proxima_accion',$any($event.target).value)"><textarea class="rounded bg-slate-900 p-2" [value]="seguimiento(p).notas" (input)="cambiar(p,'notas',$any($event.target).value)" placeholder="Notas de seguimiento"></textarea><button class="rounded border border-cyan-400 p-2 text-cyan-200" (click)="guardar(p,true)">{{seguimiento(p).asignado_a_mi?'Guardar seguimiento':'Tomar y guardar seguimiento'}}</button></div></article>}</div></section></main>` })
export class ReporteSuscripcionesComponent {
  private readonly supabase=inject(SupabaseService); readonly prospectos=signal<ProspectoSuscripcion[]>([]); readonly error=signal<string|null>(null); readonly seguimientos=signal<Record<string,SeguimientoComercial>>({}); readonly vendedores=signal<Vendedor[]>([]); readonly esAdmin=signal(false); readonly estados=['Nuevo','Contactado','Visita agendada','Interesado','Suscripción activa','Descartado']; mes=new Date().toISOString().slice(0,7);
  constructor(){void this.cargar();} clave(p:ProspectoSuscripcion){return `${p.tipo}:${p.id_entidad}`;} seguimiento(p:ProspectoSuscripcion):SeguimientoComercial{return this.seguimientos()[this.clave(p)]??{tipo_entidad:p.tipo,id_entidad:p.id_entidad,estado:'Nuevo',proxima_accion:null,notas:'',asignado_a_mi:false,id_responsable:null,responsable_email:null};}
  cambiar(p:ProspectoSuscripcion,campo:'estado'|'proxima_accion'|'notas',valor:string){this.seguimientos.update(x=>({...x,[this.clave(p)]:{...this.seguimiento(p),[campo]:valor}}));}
  async cargar(){try{const rol=await this.supabase.obtenerRolBackoffice();this.esAdmin.set(rol==='admin');const [p,s,v]=await Promise.all([this.supabase.obtenerProspectosSuscripcion(this.mes),this.supabase.obtenerSeguimientosComerciales(),rol==='admin'?this.supabase.obtenerVendedores():Promise.resolve([])]);this.prospectos.set(p);this.seguimientos.set(Object.fromEntries(s.map(x=>[`${x.tipo_entidad}:${x.id_entidad}`,x])));this.vendedores.set(v);this.error.set(null);}catch{this.error.set('No tienes permisos para consultar este reporte.');}}
  async asignar(p:ProspectoSuscripcion,idVendedor:string){if(!idVendedor)return;try{await this.supabase.asignarVendedorATaller(p.id_entidad,idVendedor);await this.cargar();}catch{this.error.set('No fue posible asignar el vendedor.');}}
  async guardar(p:ProspectoSuscripcion,asignarme:boolean){try{const s=this.seguimiento(p);await this.supabase.guardarSeguimientoComercial(p.tipo,p.id_entidad,s.estado,s.proxima_accion??'',s.notas,asignarme&&!this.esAdmin());await this.cargar();}catch{this.error.set('No fue posible guardar el seguimiento.');}}
  whatsapp(p:ProspectoSuscripcion){return `https://wa.me/${p.whatsapp.replace(/\D/g,'')}`;}
}
