-- Un taller puede tener varios navegadores/dispositivos registrados para push.
create table if not exists public.suscripciones_push (
  id_suscripcion bigint generated by default as identity primary key,
  id_usuario uuid not null references auth.users(id) on delete cascade,
  token_fcm text not null unique,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists suscripciones_push_usuario_idx on public.suscripciones_push (id_usuario);
alter table public.suscripciones_push enable row level security;
drop trigger if exists suscripciones_push_updated_at on public.suscripciones_push;
create trigger suscripciones_push_updated_at before update on public.suscripciones_push
for each row execute function public.actualizar_updated_at();

create or replace function public.registrar_suscripcion_push(p_token_fcm text, p_user_agent text default null)
returns void language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null then raise exception 'Se requiere una sesión activa'; end if;
  if char_length(trim(coalesce(p_token_fcm, ''))) < 20 then raise exception 'Token FCM inválido'; end if;
  if not exists (select 1 from public.mecanicos where id_usuario = auth.uid() and estatus_suscripcion = 'Activo') then
    raise exception 'Solo los talleres activos pueden activar notificaciones';
  end if;
  insert into public.suscripciones_push (id_usuario, token_fcm, user_agent)
  values (auth.uid(), trim(p_token_fcm), nullif(trim(p_user_agent), ''))
  on conflict (token_fcm) do update set id_usuario = excluded.id_usuario, user_agent = excluded.user_agent, updated_at = now();
end;
$$;

revoke all on function public.registrar_suscripcion_push(text, text) from public;
grant execute on function public.registrar_suscripcion_push(text, text) to authenticated;
