-- El responsable comercial de un taller es quien genera la comisión de su primera suscripción pagada.
create table if not exists public.comisiones_vendedores (
  id_comision bigint generated by default as identity primary key,
  id_vendedor uuid not null references public.vendedores(id_usuario) on delete restrict,
  tipo_entidad text not null check (tipo_entidad = 'Taller'),
  id_entidad bigint not null references public.mecanicos(id_mecanico) on delete restrict,
  stripe_invoice_id text not null unique,
  importe_pago numeric(12,2) not null check (importe_pago >= 0),
  importe_comision numeric(12,2) check (importe_comision is null or importe_comision >= 0),
  estatus text not null default 'Pendiente' check (estatus in ('Pendiente','Pagada')),
  pagada_at timestamptz,
  created_at timestamptz not null default now(),
  unique (tipo_entidad, id_entidad)
);
alter table public.comisiones_vendedores enable row level security;

drop function if exists public.seguimientos_comerciales_actuales();
create function public.seguimientos_comerciales_actuales()
returns table (tipo_entidad text,id_entidad bigint,estado text,proxima_accion date,notas text,asignado_a_mi boolean,id_responsable uuid,responsable_email text)
language plpgsql security definer set search_path=public,auth as $$
begin
 if not exists(select 1 from public.administradores where id_usuario=auth.uid()) and not exists(select 1 from public.vendedores where id_usuario=auth.uid()) then raise exception 'No autorizado'; end if;
 return query select s.tipo_entidad,s.id_entidad,s.estado,s.proxima_accion,s.notas,s.id_responsable=auth.uid(),s.id_responsable,u.email
 from public.seguimientos_comerciales s left join auth.users u on u.id=s.id_responsable;
end; $$;

create or replace function public.vendedores_disponibles()
returns table(id_usuario uuid, email text)
language plpgsql security definer set search_path=public,auth as $$
begin
  if not exists(select 1 from public.administradores where id_usuario=auth.uid()) then raise exception 'No autorizado'; end if;
  return query select v.id_usuario,u.email from public.vendedores v join auth.users u on u.id=v.id_usuario order by u.email;
end; $$;

create or replace function public.asignar_vendedor_a_taller(p_id_taller bigint,p_id_vendedor uuid)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from public.administradores where id_usuario=auth.uid()) then raise exception 'No autorizado'; end if;
  if not exists(select 1 from public.mecanicos where id_mecanico=p_id_taller) or not exists(select 1 from public.vendedores where id_usuario=p_id_vendedor) then raise exception 'Taller o vendedor inválido'; end if;
  insert into public.seguimientos_comerciales(tipo_entidad,id_entidad,estado,id_responsable)
  values('Taller',p_id_taller,'Interesado',p_id_vendedor)
  on conflict(tipo_entidad,id_entidad) do update set id_responsable=excluded.id_responsable,updated_at=now();
end; $$;

create or replace function public.comisiones_vendedores_actuales()
returns table(id_comision bigint,nombre_taller text,vendedor_email text,importe_pago numeric,importe_comision numeric,estatus text,created_at timestamptz,pagada_at timestamptz)
language plpgsql security definer set search_path=public,auth as $$
declare v_admin boolean;
begin
  v_admin:=exists(select 1 from public.administradores where id_usuario=auth.uid());
  if not v_admin and not exists(select 1 from public.vendedores where id_usuario=auth.uid()) then raise exception 'No autorizado'; end if;
  return query select c.id_comision,m.nombre_taller,u.email,c.importe_pago,c.importe_comision,c.estatus,c.created_at,c.pagada_at
  from public.comisiones_vendedores c join public.mecanicos m on m.id_mecanico=c.id_entidad join auth.users u on u.id=c.id_vendedor
  where v_admin or c.id_vendedor=auth.uid() order by c.created_at desc;
end; $$;

create or replace function public.marcar_comision_pagada(p_id_comision bigint,p_importe_comision numeric)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from public.administradores where id_usuario=auth.uid()) then raise exception 'No autorizado'; end if;
  if p_importe_comision is null or p_importe_comision<0 then raise exception 'Importe de comisión inválido'; end if;
  update public.comisiones_vendedores set importe_comision=p_importe_comision,estatus='Pagada',pagada_at=now() where id_comision=p_id_comision and estatus='Pendiente';
  if not found then raise exception 'Comisión no disponible'; end if;
end; $$;

-- La función se invoca exclusivamente desde el webhook con la service role.
create or replace function public.registrar_primer_pago_vendedor(p_tipo_entidad text,p_id_entidad bigint,p_stripe_invoice_id text,p_importe_pago numeric)
returns void language plpgsql security definer set search_path=public as $$
declare v_vendedor uuid;
begin
  if p_tipo_entidad <> 'Taller' then return; end if;
  select id_responsable into v_vendedor from public.seguimientos_comerciales where tipo_entidad='Taller' and id_entidad=p_id_entidad;
  if v_vendedor is null then return; end if;
  insert into public.comisiones_vendedores(id_vendedor,tipo_entidad,id_entidad,stripe_invoice_id,importe_pago)
  values(v_vendedor,'Taller',p_id_entidad,p_stripe_invoice_id,p_importe_pago)
  on conflict do nothing;
  if found then
    insert into public.notificaciones_push(id_usuario_destino,titulo,mensaje,url_destino)
    select a.id_usuario,'Primer pago recibido',format('%s pagó su primera suscripción. Hay una comisión pendiente para %s.',m.nombre_taller,p_importe_pago::text),'/comisiones'
    from public.administradores a join public.mecanicos m on m.id_mecanico=p_id_entidad;
  end if;
end; $$;

-- Los administradores también pueden registrar su dispositivo para recibir el aviso push.
create or replace function public.registrar_suscripcion_push(p_token_fcm text, p_user_agent text default null)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not exists (select 1 from public.mecanicos where id_usuario = auth.uid() and estatus_suscripcion = 'Activo')
     and not exists (select 1 from public.administradores where id_usuario = auth.uid()) then
    raise exception 'Solo los talleres activos o administradores pueden activar notificaciones';
  end if;
  insert into public.suscripciones_push (id_usuario, token_fcm, user_agent)
  values (auth.uid(), p_token_fcm, p_user_agent)
  on conflict (id_usuario, token_fcm) do update set user_agent=excluded.user_agent,updated_at=now();
end; $$;

revoke all on function public.vendedores_disponibles(),public.asignar_vendedor_a_taller(bigint,uuid),public.comisiones_vendedores_actuales(),public.marcar_comision_pagada(bigint,numeric),public.registrar_primer_pago_vendedor(text,bigint,text,numeric) from public;
revoke all on function public.seguimientos_comerciales_actuales() from public;
grant execute on function public.vendedores_disponibles(),public.asignar_vendedor_a_taller(bigint,uuid),public.comisiones_vendedores_actuales(),public.marcar_comision_pagada(bigint,numeric) to authenticated;
grant execute on function public.seguimientos_comerciales_actuales() to authenticated;
grant execute on function public.registrar_primer_pago_vendedor(text,bigint,text,numeric) to service_role;
