do $$ begin
  create type public.estatus_solicitud_refaccion as enum ('Abierta', 'Aceptada', 'Cancelada');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.estatus_oferta_refaccion as enum ('Pendiente', 'Aceptada', 'Rechazada');
exception when duplicate_object then null;
end $$;

create table if not exists public.solicitudes_refacciones (
  id_solicitud bigint generated by default as identity primary key,
  id_ticket bigint not null references public.tickets(id_ticket) on delete cascade,
  id_mecanico bigint not null references public.mecanicos(id_mecanico) on delete cascade,
  id_tienda_asignada bigint references public.tiendas_refacciones(id_tienda) on delete set null,
  descripcion text not null check (char_length(trim(descripcion)) between 3 and 1000),
  estatus public.estatus_solicitud_refaccion not null default 'Abierta',
  accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((estatus = 'Aceptada') = (id_tienda_asignada is not null and accepted_at is not null))
);

create table if not exists public.ofertas_refacciones (
  id_oferta bigint generated by default as identity primary key,
  id_solicitud bigint not null references public.solicitudes_refacciones(id_solicitud) on delete cascade,
  id_tienda bigint not null references public.tiendas_refacciones(id_tienda) on delete cascade,
  precio_estimado numeric(10, 2) not null check (precio_estimado >= 0),
  tiempo_estimado_minutos integer not null check (tiempo_estimado_minutos between 1 and 10080),
  mensaje text check (char_length(mensaje) <= 500),
  estatus public.estatus_oferta_refaccion not null default 'Pendiente',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id_solicitud, id_tienda)
);

create index if not exists solicitudes_refacciones_mecanico_idx on public.solicitudes_refacciones (id_mecanico, created_at desc);
create index if not exists solicitudes_refacciones_tienda_mes_idx on public.solicitudes_refacciones (id_tienda_asignada, accepted_at desc) where estatus = 'Aceptada';
create index if not exists ofertas_refacciones_solicitud_idx on public.ofertas_refacciones (id_solicitud, estatus);

drop trigger if exists solicitudes_refacciones_updated_at on public.solicitudes_refacciones;
create trigger solicitudes_refacciones_updated_at before update on public.solicitudes_refacciones for each row execute function public.actualizar_updated_at();
drop trigger if exists ofertas_refacciones_updated_at on public.ofertas_refacciones;
create trigger ofertas_refacciones_updated_at before update on public.ofertas_refacciones for each row execute function public.actualizar_updated_at();

alter table public.solicitudes_refacciones enable row level security;
alter table public.ofertas_refacciones enable row level security;

create or replace function public.crear_solicitud_refacciones(p_id_ticket bigint, p_descripcion text)
returns setof public.solicitudes_refacciones language plpgsql security definer set search_path = public as $$
declare v_mecanico bigint; v_solicitud public.solicitudes_refacciones;
begin
  select id_mecanico into v_mecanico from public.mecanicos where id_usuario = auth.uid() and estatus_suscripcion = 'Activo';
  if v_mecanico is null then raise exception 'Taller no autorizado'; end if;
  if char_length(trim(coalesce(p_descripcion, ''))) not between 3 and 1000 then raise exception 'Describe las refacciones requeridas'; end if;
  if not exists (select 1 from public.tickets where id_ticket = p_id_ticket and id_mecanico_asignado = v_mecanico and estatus = 'Asignado') then raise exception 'El servicio no está asignado a tu taller'; end if;
  if not exists (select 1 from public.tiendas_refacciones where estatus <> 'Suspendido' and (id_mecanico_invitador = v_mecanico or id_mecanico_invitador is null)) then raise exception 'No hay tiendas de refacciones disponibles para este taller'; end if;
  insert into public.solicitudes_refacciones (id_ticket, id_mecanico, descripcion) values (p_id_ticket, v_mecanico, trim(p_descripcion)) returning * into v_solicitud;
  return next v_solicitud;
end; $$;

create or replace function public.solicitudes_refacciones_para_tienda()
returns table (id_solicitud bigint, id_ticket bigint, descripcion text, ubicacion_auto text, nombre_taller text, created_at timestamptz)
language sql security definer set search_path = public as $$
  select s.id_solicitud, s.id_ticket, s.descripcion, t.ubicacion_auto, m.nombre_taller, s.created_at
  from public.solicitudes_refacciones s
  join public.tiendas_refacciones tr on tr.id_usuario = auth.uid()
  join public.tickets t on t.id_ticket = s.id_ticket
  join public.mecanicos m on m.id_mecanico = s.id_mecanico
  where s.estatus = 'Abierta' and tr.estatus <> 'Suspendido'
    and (tr.id_mecanico_invitador = s.id_mecanico or tr.id_mecanico_invitador is null)
  order by s.created_at asc;
$$;

create or replace function public.enviar_oferta_refacciones(p_id_solicitud bigint, p_precio_estimado numeric, p_tiempo_estimado_minutos integer, p_mensaje text default null)
returns setof public.ofertas_refacciones language plpgsql security definer set search_path = public as $$
declare v_tienda bigint; v_oferta public.ofertas_refacciones;
begin
  select id_tienda into v_tienda from public.tiendas_refacciones where id_usuario = auth.uid() and estatus <> 'Suspendido';
  if v_tienda is null then raise exception 'Tienda no autorizada'; end if;
  if p_precio_estimado is null or p_precio_estimado < 0 or p_tiempo_estimado_minutos not between 1 and 10080 then raise exception 'Oferta inválida'; end if;
  if not exists (select 1 from public.solicitudes_refacciones s join public.tiendas_refacciones tr on tr.id_tienda = v_tienda where s.id_solicitud = p_id_solicitud and s.estatus = 'Abierta' and (tr.id_mecanico_invitador = s.id_mecanico or tr.id_mecanico_invitador is null)) then raise exception 'La solicitud no está disponible'; end if;
  insert into public.ofertas_refacciones (id_solicitud, id_tienda, precio_estimado, tiempo_estimado_minutos, mensaje)
  values (p_id_solicitud, v_tienda, p_precio_estimado, p_tiempo_estimado_minutos, nullif(trim(p_mensaje), ''))
  on conflict (id_solicitud, id_tienda) do update set precio_estimado = excluded.precio_estimado, tiempo_estimado_minutos = excluded.tiempo_estimado_minutos, mensaje = excluded.mensaje, updated_at = now() where ofertas_refacciones.estatus = 'Pendiente'
  returning * into v_oferta;
  if v_oferta is null then raise exception 'Esta oferta ya no se puede modificar'; end if;
  return next v_oferta;
end; $$;

create or replace function public.ofertas_refacciones_para_taller()
returns table (id_oferta bigint, id_solicitud bigint, id_ticket bigint, descripcion text, nombre_tienda text, precio_estimado numeric, tiempo_estimado_minutos integer, mensaje text, created_at timestamptz)
language sql security definer set search_path = public as $$
  select o.id_oferta, s.id_solicitud, s.id_ticket, s.descripcion, tr.nombre_tienda, o.precio_estimado, o.tiempo_estimado_minutos, o.mensaje, o.created_at
  from public.ofertas_refacciones o join public.solicitudes_refacciones s on s.id_solicitud = o.id_solicitud join public.tiendas_refacciones tr on tr.id_tienda = o.id_tienda join public.mecanicos m on m.id_mecanico = s.id_mecanico
  where m.id_usuario = auth.uid() and o.estatus = 'Pendiente' and s.estatus = 'Abierta'
  order by o.created_at asc;
$$;

create or replace function public.aceptar_oferta_refacciones(p_id_oferta bigint)
returns setof public.solicitudes_refacciones language plpgsql security definer set search_path = public as $$
declare v_oferta public.ofertas_refacciones; v_solicitud public.solicitudes_refacciones;
begin
  select * into v_oferta from public.ofertas_refacciones where id_oferta = p_id_oferta and estatus = 'Pendiente' for update;
  if not found then raise exception 'La oferta ya no está disponible'; end if;
  select s.* into v_solicitud from public.solicitudes_refacciones s join public.mecanicos m on m.id_mecanico = s.id_mecanico where s.id_solicitud = v_oferta.id_solicitud and s.estatus = 'Abierta' and m.id_usuario = auth.uid() for update;
  if not found then raise exception 'La solicitud no está disponible'; end if;
  update public.solicitudes_refacciones set estatus = 'Aceptada', id_tienda_asignada = v_oferta.id_tienda, accepted_at = now() where id_solicitud = v_solicitud.id_solicitud returning * into v_solicitud;
  update public.ofertas_refacciones set estatus = 'Aceptada', updated_at = now() where id_oferta = p_id_oferta;
  update public.ofertas_refacciones set estatus = 'Rechazada', updated_at = now() where id_solicitud = v_solicitud.id_solicitud and id_oferta <> p_id_oferta and estatus = 'Pendiente';
  return next v_solicitud;
end; $$;

revoke all on function public.crear_solicitud_refacciones(bigint, text), public.solicitudes_refacciones_para_tienda(), public.enviar_oferta_refacciones(bigint, numeric, integer, text), public.ofertas_refacciones_para_taller(), public.aceptar_oferta_refacciones(bigint) from public;
grant execute on function public.crear_solicitud_refacciones(bigint, text), public.solicitudes_refacciones_para_tienda(), public.enviar_oferta_refacciones(bigint, numeric, integer, text), public.ofertas_refacciones_para_taller(), public.aceptar_oferta_refacciones(bigint) to authenticated;
