-- Flujo de cotizaciones: un taller propone una oferta y el cliente elige una.
do $$ begin
  create type public.estatus_oferta_ticket as enum ('Pendiente', 'Aceptada', 'Rechazada', 'Expirada');
exception when duplicate_object then null;
end $$;

create table if not exists public.ofertas_ticket (
  id_oferta bigint generated by default as identity primary key,
  id_ticket bigint not null references public.tickets(id_ticket) on delete cascade,
  id_mecanico bigint not null references public.mecanicos(id_mecanico) on delete cascade,
  precio_estimado numeric(10, 2) not null check (precio_estimado >= 0),
  tiempo_estimado_minutos integer not null check (tiempo_estimado_minutos between 1 and 1440),
  mensaje text check (char_length(mensaje) <= 500),
  estatus public.estatus_oferta_ticket not null default 'Pendiente',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id_ticket, id_mecanico)
);

create index if not exists ofertas_ticket_ticket_pendientes_idx
  on public.ofertas_ticket (id_ticket, created_at asc) where estatus = 'Pendiente';
create index if not exists ofertas_ticket_mecanico_idx on public.ofertas_ticket (id_mecanico);

drop trigger if exists ofertas_ticket_updated_at on public.ofertas_ticket;
create trigger ofertas_ticket_updated_at before update on public.ofertas_ticket
for each row execute function public.actualizar_updated_at();

alter table public.ofertas_ticket enable row level security;
drop policy if exists "Taller ve sus ofertas" on public.ofertas_ticket;
drop policy if exists "Solicitante ve ofertas de su ticket" on public.ofertas_ticket;
create policy "Taller ve sus ofertas" on public.ofertas_ticket for select to authenticated
using (id_mecanico in (select id_mecanico from public.mecanicos where id_usuario = auth.uid()));
create policy "Solicitante ve ofertas de su ticket" on public.ofertas_ticket for select to authenticated
using (exists (select 1 from public.tickets where id_ticket = ofertas_ticket.id_ticket and id_usuario_solicitante = auth.uid()));

-- Permite que Realtime entregue al taller el cambio cuando el cliente elige
-- su oferta, sin darle visibilidad de tickets abiertos de otros talleres.
drop policy if exists "Taller ve tickets asignados" on public.tickets;
create policy "Taller ve tickets asignados" on public.tickets for select to authenticated
using (id_mecanico_asignado in (select id_mecanico from public.mecanicos where id_usuario = auth.uid()));

-- Las solicitudes abiertas no exponen identidad ni teléfono del cliente. Los datos
-- solo se entregan por tickets_asignados_del_taller después de ser elegido.
drop function if exists public.tickets_abiertos_para_taller(double precision);
create function public.tickets_abiertos_para_taller(p_radio_metros double precision default 5000)
returns table (id_ticket bigint, id_cliente bigint, descripcion_falla text, ubicacion_auto text, estatus public.tipo_estatus_ticket, id_mecanico_asignado bigint, created_at timestamptz, updated_at timestamptz, cliente jsonb)
language plpgsql security definer set search_path = public, extensions as $$
begin
  if auth.uid() is null then raise exception 'Se requiere una sesión activa'; end if;
  if p_radio_metros is null or p_radio_metros <= 0 or p_radio_metros > 50000 then raise exception 'El radio debe estar entre 0 y 50000 metros'; end if;
  return query
  select t.id_ticket, t.id_cliente, t.descripcion_falla, t.ubicacion_auto, t.estatus,
    t.id_mecanico_asignado, t.created_at, t.updated_at, null::jsonb
  from public.mecanicos m join public.tickets t on t.estatus = 'Abierto'
    and t.ubicacion is not null and extensions.ST_DWithin(m.ubicacion, t.ubicacion, p_radio_metros)
  where m.id_usuario = auth.uid() and m.estatus_suscripcion = 'Activo' and m.ubicacion is not null
  order by t.created_at asc;
end;
$$;

create or replace function public.enviar_oferta(
  p_id_ticket bigint,
  p_precio_estimado numeric,
  p_tiempo_estimado_minutos integer,
  p_mensaje text default null
)
returns setof public.ofertas_ticket
language plpgsql security definer set search_path = public, extensions as $$
declare v_mecanico bigint; v_oferta public.ofertas_ticket;
begin
  if auth.uid() is null then raise exception 'Se requiere una sesión activa'; end if;
  if p_precio_estimado is null or p_precio_estimado < 0 then raise exception 'Precio inválido'; end if;
  if p_tiempo_estimado_minutos is null or p_tiempo_estimado_minutos not between 1 and 1440 then raise exception 'Tiempo estimado inválido'; end if;
  if char_length(coalesce(p_mensaje, '')) > 500 then raise exception 'El mensaje excede 500 caracteres'; end if;

  select m.id_mecanico into v_mecanico from public.mecanicos m
  where m.id_usuario = auth.uid() and m.estatus_suscripcion = 'Activo';
  if v_mecanico is null then raise exception 'Taller no autorizado'; end if;

  if not exists (
    select 1 from public.tickets t join public.mecanicos m on m.id_mecanico = v_mecanico
    where t.id_ticket = p_id_ticket and t.estatus = 'Abierto' and t.ubicacion is not null
      and m.ubicacion is not null and extensions.ST_DWithin(m.ubicacion, t.ubicacion, 5000)
  ) then raise exception 'La solicitud ya no está disponible en tu radio'; end if;

  insert into public.ofertas_ticket (id_ticket, id_mecanico, precio_estimado, tiempo_estimado_minutos, mensaje)
  values (p_id_ticket, v_mecanico, p_precio_estimado, p_tiempo_estimado_minutos, nullif(trim(p_mensaje), ''))
  on conflict (id_ticket, id_mecanico) do update set
    precio_estimado = excluded.precio_estimado, tiempo_estimado_minutos = excluded.tiempo_estimado_minutos,
    mensaje = excluded.mensaje, estatus = 'Pendiente', updated_at = now()
  where ofertas_ticket.estatus = 'Pendiente'
  returning * into v_oferta;
  if v_oferta is null then raise exception 'Esta oferta ya no se puede modificar'; end if;
  return next v_oferta;
end;
$$;

create or replace function public.ofertas_para_cliente(p_id_ticket bigint)
returns table (id_oferta bigint, id_ticket bigint, id_mecanico bigint, nombre_taller text, especialidades text[], precio_estimado numeric, tiempo_estimado_minutos integer, mensaje text, created_at timestamptz)
language sql security definer set search_path = public as $$
  select o.id_oferta, o.id_ticket, o.id_mecanico, m.nombre_taller, m.especialidades,
    o.precio_estimado, o.tiempo_estimado_minutos, o.mensaje, o.created_at
  from public.ofertas_ticket o join public.mecanicos m on m.id_mecanico = o.id_mecanico
  join public.tickets t on t.id_ticket = o.id_ticket
  where o.id_ticket = p_id_ticket and o.estatus = 'Pendiente' and t.id_usuario_solicitante = auth.uid()
  order by o.precio_estimado asc, o.tiempo_estimado_minutos asc, o.created_at asc;
$$;

create or replace function public.aceptar_oferta(p_id_oferta bigint)
returns setof public.tickets
language plpgsql security definer set search_path = public as $$
declare v_oferta public.ofertas_ticket; v_ticket public.tickets;
begin
  if auth.uid() is null then raise exception 'Se requiere una sesión activa'; end if;
  select o.* into v_oferta from public.ofertas_ticket o where o.id_oferta = p_id_oferta and o.estatus = 'Pendiente' for update;
  if not found then raise exception 'La oferta ya no está disponible' using errcode = 'P0002'; end if;
  select * into v_ticket from public.tickets where id_ticket = v_oferta.id_ticket and id_usuario_solicitante = auth.uid() and estatus = 'Abierto' for update;
  if not found then raise exception 'La solicitud ya no está disponible' using errcode = 'P0002'; end if;
  update public.tickets set estatus = 'Asignado', id_mecanico_asignado = v_oferta.id_mecanico where id_ticket = v_ticket.id_ticket returning * into v_ticket;
  update public.ofertas_ticket set estatus = 'Aceptada', updated_at = now() where id_oferta = p_id_oferta;
  update public.ofertas_ticket set estatus = 'Rechazada', updated_at = now() where id_ticket = v_ticket.id_ticket and id_oferta <> p_id_oferta and estatus = 'Pendiente';
  return next v_ticket;
end;
$$;

revoke all on function public.aceptar_ticket(bigint) from authenticated;
revoke all on function public.tickets_abiertos_para_taller(double precision) from public;
grant execute on function public.tickets_abiertos_para_taller(double precision) to authenticated;
revoke all on function public.enviar_oferta(bigint, numeric, integer, text) from public;
grant execute on function public.enviar_oferta(bigint, numeric, integer, text) to authenticated;
revoke all on function public.ofertas_para_cliente(bigint) from public;
grant execute on function public.ofertas_para_cliente(bigint) to authenticated;
revoke all on function public.aceptar_oferta(bigint) from public;
grant execute on function public.aceptar_oferta(bigint) to authenticated;

do $$ begin alter publication supabase_realtime add table public.ofertas_ticket; exception when duplicate_object then null; end $$;
