create table if not exists public.tiendas_refacciones (
  id_tienda bigint generated by default as identity primary key,
  id_usuario uuid not null unique references auth.users(id) on delete cascade,
  id_mecanico_invitador bigint references public.mecanicos(id_mecanico) on delete set null,
  nombre_tienda text not null check (char_length(trim(nombre_tienda)) between 2 and 160),
  whatsapp_destino text not null check (char_length(regexp_replace(whatsapp_destino, '\\D', '', 'g')) between 10 and 15),
  zona_cobertura text not null check (char_length(trim(zona_cobertura)) between 2 and 200),
  radio_cobertura_metros integer not null default 5000 check (radio_cobertura_metros in (3000, 5000, 10000, 20000)),
  ubicacion extensions.geography(Point, 4326),
  estatus text not null default 'Pendiente' check (estatus in ('Pendiente', 'Activo', 'Suspendido')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tiendas_refacciones_ubicacion_gist_idx
  on public.tiendas_refacciones using gist (ubicacion);
create index if not exists tiendas_refacciones_invitador_idx
  on public.tiendas_refacciones (id_mecanico_invitador);

alter table public.tiendas_refacciones enable row level security;

create policy "Tienda ve su propio perfil" on public.tiendas_refacciones
  for select to authenticated using (id_usuario = auth.uid());

comment on table public.tiendas_refacciones is
  'Tiendas invitadas por un taller o administrador para futuras cotizaciones de refacciones.';
