-- Cola transaccional: un webhook de Supabase procesará cada fila INSERT.
create table if not exists public.notificaciones_push (
  id_notificacion bigint generated by default as identity primary key,
  id_ticket bigint not null unique references public.tickets(id_ticket) on delete cascade,
  estatus text not null default 'Pendiente' check (estatus in ('Pendiente', 'Enviando', 'Enviado', 'Error')),
  intentos integer not null default 0,
  enviados integer not null default 0,
  ultimo_error text,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);
alter table public.notificaciones_push enable row level security;

create or replace function public.encolar_notificacion_ticket()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.estatus = 'Abierto' and new.ubicacion is not null then
    insert into public.notificaciones_push (id_ticket) values (new.id_ticket)
    on conflict (id_ticket) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists tickets_encolar_notificacion on public.tickets;
create trigger tickets_encolar_notificacion after insert on public.tickets
for each row execute function public.encolar_notificacion_ticket();

-- Solo la Edge Function, mediante la clave de servidor, puede recuperar tokens.
create or replace function public.tokens_push_para_ticket(p_id_ticket bigint)
returns table (token_fcm text, id_mecanico bigint, nombre_taller text)
language sql security definer set search_path = public, extensions as $$
  select s.token_fcm, m.id_mecanico, m.nombre_taller
  from public.tickets t
  join public.mecanicos m on m.estatus_suscripcion = 'Activo' and m.ubicacion is not null
    and extensions.ST_DWithin(m.ubicacion, t.ubicacion, m.radio_cobertura_metros)
  join public.suscripciones_push s on s.id_usuario = m.id_usuario
  where t.id_ticket = p_id_ticket and t.estatus = 'Abierto' and t.ubicacion is not null;
$$;

revoke all on function public.tokens_push_para_ticket(bigint) from public;
grant execute on function public.tokens_push_para_ticket(bigint) to service_role;
